apiVersion: v1
kind: ServiceAccount
metadata:
  name: customers-service
  labels:
    app.kubernetes.io/name: customers-service
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/component: service
    app.kubernetes.io/managed-by: Helm
