{{- if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "petclinic-service.configMapName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "petclinic-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ tpl (toString $value) $ | quote }}
  {{- end }}
{{- end }}
