apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "petclinic-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default .Values.containerPort }}
      protocol: TCP
  selector:
    {{- include "petclinic-service.selectorLabels" . | nindent 4 }}
