apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/component: gateway
    app.kubernetes.io/managed-by: Helm
data:
  CONFIG_SERVER_URL: "http://config-server:8888"
  DISCOVERY_SERVER_URL: "http://discovery-server:8761/eureka"
