apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  labels:
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8761
      targetPort: 8761
      protocol: TCP
  selector:
    app.kubernetes.io/name: discovery-server
