apiVersion: v1
kind: ServiceAccount
metadata:
  name: discovery-server
  labels:
    app.kubernetes.io/name: discovery-server
    app.kubernetes.io/part-of: petclinic
    app.kubernetes.io/component: server
    app.kubernetes.io/managed-by: Helm
